package render

import (
	"bufio"
	"os"
	"sync"
)

//-----------------------------------------------------------------------------

// Define the ABAQUS or CalculiX inp file sections.

type Separator struct {
	Comma byte
	Space byte
}

func NewSep() Separator {
	return Separator{
		Comma: 0x2C, // Comma ASCII Character in hexadecimal.
		Space: 0x20, // Space ASCII Character in hexadecimal.
	}
}

type InpNode struct {
	Id  uint32    //
	sep Separator //
}

//-----------------------------------------------------------------------------

// writeFE writes a stream of finite elements in the shape of tetrahedra to an ABAQUS or CalculiX file.
func writeFE(wg *sync.WaitGroup, path string) (chan<- []*Tetrahedron, error) {
	f, err := os.Create(path)
	if err != nil {
		return nil, err
	}

	// Use buffered IO for optimal IO writes.
	// The default buffer size doesn't appear to limit performance.
	buf := bufio.NewWriter(f)

	_, err = f.WriteString("**\n** Structure: finite elements of a 3D model.\n** Generated by: https://github.com/deadsy/sdfx\n**\n")
	if err != nil {
		return nil, err
	}

	_, err = f.WriteString("*HEADING\nModel: 3D model Date: N/A\n")
	if err != nil {
		return nil, err
	}

	_, err = f.WriteString("*NODE\n")
	if err != nil {
		return nil, err
	}

	// External code writes tetrahedra to this channel.
	// This goroutine reads the channel and writes tetrahedra to the file.
	c := make(chan []*Tetrahedron)

	wg.Add(1)
	go func() {
		defer wg.Done()
		defer f.Close()

		// read tetrahedra from the channel and write them to the file
		for ts := range c {
			for _, t := range ts {
				_ = t
				// TODO.
			}
		}

		// flush the tetrahedra
		buf.Flush()
	}()

	return c, nil
}
